{{- range $app := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ $.Values.project }}-{{ $app.name }}-github-workflow-sensor
  namespace: {{ $.Values.project }}
spec:
  eventBusName: {{ $.Values.project }}-ci-eventbus
  template:
    serviceAccountName: {{ $.Values.project }}-ci-workflow-sa
  dependencies:
    - name: github-dep
      eventSourceName: {{ $.Values.project }}-{{ $app.name }}-github-eventsource
      eventName: {{ $.Values.project }}-{{ $app.name }}-github-trigger
      filters:
        data:
          - path: body.zen
            type: string
            value:
              - ""
            comparator: "!="
            template: "ping"
          - path: body.ref
            type: string
            comparator: "="
            value:
              - "refs/heads/{{ $app.git.branch }}"
            template: "push"
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: {{ $.Values.project }}-{{ $app.name }}-build-workflow-
              spec:
                arguments:
                  parameters:
                    - name: git_sha
                    - name: event_type
                workflowTemplateRef:
                  name: {{ $.Values.project }}-{{ $app.name }}-build-workflow-template
          parameters:
            - src:
                dependencyName: github-dep
                dataKey: body.after
                value: "latest"
                dataTemplate: "{{ `{{ if eq .Input.body.zen \"\" }}{{ .Input.body.after }}{{ else }}latest{{ end }}` }}"
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: github-dep
                value: "ping"
                dataTemplate: "{{ `{{ if ne .Input.body.zen \"\" }}ping{{ else }}push{{ end }}` }}"
              dest: spec.arguments.parameters.1.value
      retryStrategy:
        steps: 3
{{- end }}
